### ISSUE TITLE
Tasks for MEAN CRUD - Travel Tracker

### ISSUE THREAD

**Issue by secdevyc** [secdevyc/traveltracker#2]
- [x] Create Controller - ALEX
- [x] Initialize Mongoose- ALEX
- [x] Create Travel Tracker model - ALEX
- [x] Create Create Route - YULLI
- [x] Create Index Route - YULLI
- [x] Create Delete Route - YULLI
- [x] Create Update Route - YULLI
============
Public Files 
============
- [x] Create Index.html - ALEX
- [x] Setup Angular -  ALEX
- [x] Create App/Controller - - ALEX
- [x] Create New Travel-Tracker form  - ALEX
- [x] Setup AJAX POST request to db - ALEX
- [x] Create GET function and request - YULLI
- [x] Toggle all travel info under destination name - YULLI
- [x] Create Delete function/request - YULLI
- [x] Create Edit function/request - YULLI
============
READ ME 
========
- [x] Added content to readme.md - BOTH
============
CSS
==========
- [x] Added styling - BOTH

**Comment by ahawkz** [comment]
working on creating controller - controller set up

**Comment by ahawkz** [comment]
connected to mongoose

**Comment by ahawkz** [comment]
backend ready for API routes

**Comment by secdevyc** [comment]
added GET, DELETE, PUT AND CREATE routes

**Comment by secdevyc** [comment]
completed first pairprogramming project.
